### ISSUE TITLE
Unit testing the RDFContainer class.

### ISSUE THREAD

**Issue by KonradSuli** [BME-MIT-IET/Mind1-iet-2018#7]
Writing unit tests for the methods mentioned above found in the class QueryEngine.

**Comment by Molnarmala** [comment]
Just pushed a branch with some sample code.

**Comment by Molnarmala** [comment]
Edit: to make use of the project for testing the rdfsharp project you must first add it's reference to the unit test project . Sorry for missing it.

Also I think we should you mocks for at least the parameters, because of the complexity of the funcions.
I suggest [moq](https://www.nuget.org/packages/moq/) package to be used. 
Also [here](https://github.com/moq/moq4) is the implementation and some sample code for it.

**Comment by KonradSuli** [comment]
Change of plans due to complexity issues.

**Comment by FTim** [comment]
Some new tests added.

**Comment by Molnarmala** [comment]
It seems the testing is concluded 
![containerfin](https://user-images.githubusercontent.com/26526210/40282400-068bc99e-5c6f-11e8-848a-9f70764e3e56.PNG)
