### ISSUE TITLE
Need some new tests for better coverage

### ISSUE THREAD

**Issue by FTim** [BME-MIT-IET/Mind1-iet-2018#8]
We wrote some tests for RDFContainer class, but not sure about the coverage, can somebody check it and write some new tests if its necessary?

**Comment by Molnarmala** [comment]
I've done a coverage for your current test. The results are :

![image](https://user-images.githubusercontent.com/26526210/40275497-8437743a-5bf0-11e8-90f1-b8b3a4da68d9.png)

It turns out we missed all blocks where the containers type is not ALT. So many test for the add and remove functions, yet we missed this. 
The other functions are mostly getters with nullchecks, so not the biggest thing ever.

**Comment by jaklia** [comment]
I added the missing tests for BAG and SEQ type containers

**Comment by FTim** [comment]
Seems fine. Need coverage and its done.

**Comment by Molnarmala** [comment]
In the end the coverages are:
![allfullminden](https://user-images.githubusercontent.com/26526210/40282567-a1da9fd6-5c71-11e8-87ea-9fb208f79b7d.PNG)

For greater detail check the [Test Coverage Wiki](https://github.com/BME-MIT-IET/Mind1-iet-2018/wiki/Test-coverage)
